/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TerminosRouteImport } from './routes/terminos'
import { Route as TecnologiaRouteImport } from './routes/tecnologia'
import { Route as TalentoHumanoRouteImport } from './routes/talento-humano'
import { Route as SuperadminRouteImport } from './routes/superadmin'
import { Route as SobreRouteImport } from './routes/sobre'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ProfesionalesRouteImport } from './routes/profesionales'
import { Route as PrivacidadRouteImport } from './routes/privacidad'
import { Route as PrensaRouteImport } from './routes/prensa'
import { Route as PlanesRouteImport } from './routes/planes'
import { Route as MensajesRouteImport } from './routes/mensajes'
import { Route as HabeasDataRouteImport } from './routes/habeas-data'
import { Route as FamiliasRouteImport } from './routes/familias'
import { Route as EvaluadorRouteImport } from './routes/evaluador'
import { Route as EnfermeriaDomiciliariaRouteImport } from './routes/enfermeria-domiciliaria'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as CumplimientoRouteImport } from './routes/cumplimiento'
import { Route as CuidadorDomicilioRouteImport } from './routes/cuidador-domicilio'
import { Route as CuidadoPostoperatorioRouteImport } from './routes/cuidado-postoperatorio'
import { Route as CuidadoPediatricoRouteImport } from './routes/cuidado-pediatrico'
import { Route as CuidadoPaliativoRouteImport } from './routes/cuidado-paliativo'
import { Route as CuidadoAdultoMayorRouteImport } from './routes/cuidado-adulto-mayor'
import { Route as ContactoRouteImport } from './routes/contacto'
import { Route as CarrerasRouteImport } from './routes/carreras'
import { Route as BuscarRouteImport } from './routes/buscar'
import { Route as AuxiliarEnfermeriaRouteImport } from './routes/auxiliar-enfermeria'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SuperadminIndexRouteImport } from './routes/superadmin.index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard.index'
import { Route as SuperadminPublicidadRouteImport } from './routes/superadmin.publicidad'
import { Route as SuperadminMarketplaceRouteImport } from './routes/superadmin.marketplace'
import { Route as SuperadminMarketingRouteImport } from './routes/superadmin.marketing'
import { Route as SuperadminFraudeRouteImport } from './routes/superadmin.fraude'
import { Route as SuperadminCrmRouteImport } from './routes/superadmin.crm'
import { Route as SuperadminAuditoriaRouteImport } from './routes/superadmin.auditoria'
import { Route as ServicioBookingIdRouteImport } from './routes/servicio.$bookingId'
import { Route as ProfesionalProIdRouteImport } from './routes/profesional.$proId'
import { Route as OfertaOfferIdRouteImport } from './routes/oferta.$offerId'
import { Route as DashboardWhatsappRouteImport } from './routes/dashboard.whatsapp'
import { Route as DashboardProfesionalRouteImport } from './routes/dashboard.profesional'
import { Route as DashboardInstitucionRouteImport } from './routes/dashboard.institucion'
import { Route as DashboardFamiliaRouteImport } from './routes/dashboard.familia'
import { Route as DashboardFamiliaOnboardingRouteImport } from './routes/dashboard.familia.onboarding'

const TerminosRoute = TerminosRouteImport.update({
  id: '/terminos',
  path: '/terminos',
  getParentRoute: () => rootRouteImport,
} as any)
const TecnologiaRoute = TecnologiaRouteImport.update({
  id: '/tecnologia',
  path: '/tecnologia',
  getParentRoute: () => rootRouteImport,
} as any)
const TalentoHumanoRoute = TalentoHumanoRouteImport.update({
  id: '/talento-humano',
  path: '/talento-humano',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperadminRoute = SuperadminRouteImport.update({
  id: '/superadmin',
  path: '/superadmin',
  getParentRoute: () => rootRouteImport,
} as any)
const SobreRoute = SobreRouteImport.update({
  id: '/sobre',
  path: '/sobre',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfesionalesRoute = ProfesionalesRouteImport.update({
  id: '/profesionales',
  path: '/profesionales',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadRoute = PrivacidadRouteImport.update({
  id: '/privacidad',
  path: '/privacidad',
  getParentRoute: () => rootRouteImport,
} as any)
const PrensaRoute = PrensaRouteImport.update({
  id: '/prensa',
  path: '/prensa',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanesRoute = PlanesRouteImport.update({
  id: '/planes',
  path: '/planes',
  getParentRoute: () => rootRouteImport,
} as any)
const MensajesRoute = MensajesRouteImport.update({
  id: '/mensajes',
  path: '/mensajes',
  getParentRoute: () => rootRouteImport,
} as any)
const HabeasDataRoute = HabeasDataRouteImport.update({
  id: '/habeas-data',
  path: '/habeas-data',
  getParentRoute: () => rootRouteImport,
} as any)
const FamiliasRoute = FamiliasRouteImport.update({
  id: '/familias',
  path: '/familias',
  getParentRoute: () => rootRouteImport,
} as any)
const EvaluadorRoute = EvaluadorRouteImport.update({
  id: '/evaluador',
  path: '/evaluador',
  getParentRoute: () => rootRouteImport,
} as any)
const EnfermeriaDomiciliariaRoute = EnfermeriaDomiciliariaRouteImport.update({
  id: '/enfermeria-domiciliaria',
  path: '/enfermeria-domiciliaria',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const CumplimientoRoute = CumplimientoRouteImport.update({
  id: '/cumplimiento',
  path: '/cumplimiento',
  getParentRoute: () => rootRouteImport,
} as any)
const CuidadorDomicilioRoute = CuidadorDomicilioRouteImport.update({
  id: '/cuidador-domicilio',
  path: '/cuidador-domicilio',
  getParentRoute: () => rootRouteImport,
} as any)
const CuidadoPostoperatorioRoute = CuidadoPostoperatorioRouteImport.update({
  id: '/cuidado-postoperatorio',
  path: '/cuidado-postoperatorio',
  getParentRoute: () => rootRouteImport,
} as any)
const CuidadoPediatricoRoute = CuidadoPediatricoRouteImport.update({
  id: '/cuidado-pediatrico',
  path: '/cuidado-pediatrico',
  getParentRoute: () => rootRouteImport,
} as any)
const CuidadoPaliativoRoute = CuidadoPaliativoRouteImport.update({
  id: '/cuidado-paliativo',
  path: '/cuidado-paliativo',
  getParentRoute: () => rootRouteImport,
} as any)
const CuidadoAdultoMayorRoute = CuidadoAdultoMayorRouteImport.update({
  id: '/cuidado-adulto-mayor',
  path: '/cuidado-adulto-mayor',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactoRoute = ContactoRouteImport.update({
  id: '/contacto',
  path: '/contacto',
  getParentRoute: () => rootRouteImport,
} as any)
const CarrerasRoute = CarrerasRouteImport.update({
  id: '/carreras',
  path: '/carreras',
  getParentRoute: () => rootRouteImport,
} as any)
const BuscarRoute = BuscarRouteImport.update({
  id: '/buscar',
  path: '/buscar',
  getParentRoute: () => rootRouteImport,
} as any)
const AuxiliarEnfermeriaRoute = AuxiliarEnfermeriaRouteImport.update({
  id: '/auxiliar-enfermeria',
  path: '/auxiliar-enfermeria',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperadminIndexRoute = SuperadminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SuperadminRoute,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardRoute,
} as any)
const SuperadminPublicidadRoute = SuperadminPublicidadRouteImport.update({
  id: '/publicidad',
  path: '/publicidad',
  getParentRoute: () => SuperadminRoute,
} as any)
const SuperadminMarketplaceRoute = SuperadminMarketplaceRouteImport.update({
  id: '/marketplace',
  path: '/marketplace',
  getParentRoute: () => SuperadminRoute,
} as any)
const SuperadminMarketingRoute = SuperadminMarketingRouteImport.update({
  id: '/marketing',
  path: '/marketing',
  getParentRoute: () => SuperadminRoute,
} as any)
const SuperadminFraudeRoute = SuperadminFraudeRouteImport.update({
  id: '/fraude',
  path: '/fraude',
  getParentRoute: () => SuperadminRoute,
} as any)
const SuperadminCrmRoute = SuperadminCrmRouteImport.update({
  id: '/crm',
  path: '/crm',
  getParentRoute: () => SuperadminRoute,
} as any)
const SuperadminAuditoriaRoute = SuperadminAuditoriaRouteImport.update({
  id: '/auditoria',
  path: '/auditoria',
  getParentRoute: () => SuperadminRoute,
} as any)
const ServicioBookingIdRoute = ServicioBookingIdRouteImport.update({
  id: '/servicio/$bookingId',
  path: '/servicio/$bookingId',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfesionalProIdRoute = ProfesionalProIdRouteImport.update({
  id: '/profesional/$proId',
  path: '/profesional/$proId',
  getParentRoute: () => rootRouteImport,
} as any)
const OfertaOfferIdRoute = OfertaOfferIdRouteImport.update({
  id: '/oferta/$offerId',
  path: '/oferta/$offerId',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardWhatsappRoute = DashboardWhatsappRouteImport.update({
  id: '/whatsapp',
  path: '/whatsapp',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardProfesionalRoute = DashboardProfesionalRouteImport.update({
  id: '/profesional',
  path: '/profesional',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardInstitucionRoute = DashboardInstitucionRouteImport.update({
  id: '/institucion',
  path: '/institucion',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardFamiliaRoute = DashboardFamiliaRouteImport.update({
  id: '/familia',
  path: '/familia',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardFamiliaOnboardingRoute =
  DashboardFamiliaOnboardingRouteImport.update({
    id: '/onboarding',
    path: '/onboarding',
    getParentRoute: () => DashboardFamiliaRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/auxiliar-enfermeria': typeof AuxiliarEnfermeriaRoute
  '/buscar': typeof BuscarRoute
  '/carreras': typeof CarrerasRoute
  '/contacto': typeof ContactoRoute
  '/cuidado-adulto-mayor': typeof CuidadoAdultoMayorRoute
  '/cuidado-paliativo': typeof CuidadoPaliativoRoute
  '/cuidado-pediatrico': typeof CuidadoPediatricoRoute
  '/cuidado-postoperatorio': typeof CuidadoPostoperatorioRoute
  '/cuidador-domicilio': typeof CuidadorDomicilioRoute
  '/cumplimiento': typeof CumplimientoRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/enfermeria-domiciliaria': typeof EnfermeriaDomiciliariaRoute
  '/evaluador': typeof EvaluadorRoute
  '/familias': typeof FamiliasRoute
  '/habeas-data': typeof HabeasDataRoute
  '/mensajes': typeof MensajesRoute
  '/planes': typeof PlanesRoute
  '/prensa': typeof PrensaRoute
  '/privacidad': typeof PrivacidadRoute
  '/profesionales': typeof ProfesionalesRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/superadmin': typeof SuperadminRouteWithChildren
  '/talento-humano': typeof TalentoHumanoRoute
  '/tecnologia': typeof TecnologiaRoute
  '/terminos': typeof TerminosRoute
  '/dashboard/familia': typeof DashboardFamiliaRouteWithChildren
  '/dashboard/institucion': typeof DashboardInstitucionRoute
  '/dashboard/profesional': typeof DashboardProfesionalRoute
  '/dashboard/whatsapp': typeof DashboardWhatsappRoute
  '/oferta/$offerId': typeof OfertaOfferIdRoute
  '/profesional/$proId': typeof ProfesionalProIdRoute
  '/servicio/$bookingId': typeof ServicioBookingIdRoute
  '/superadmin/auditoria': typeof SuperadminAuditoriaRoute
  '/superadmin/crm': typeof SuperadminCrmRoute
  '/superadmin/fraude': typeof SuperadminFraudeRoute
  '/superadmin/marketing': typeof SuperadminMarketingRoute
  '/superadmin/marketplace': typeof SuperadminMarketplaceRoute
  '/superadmin/publicidad': typeof SuperadminPublicidadRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/superadmin/': typeof SuperadminIndexRoute
  '/dashboard/familia/onboarding': typeof DashboardFamiliaOnboardingRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/auxiliar-enfermeria': typeof AuxiliarEnfermeriaRoute
  '/buscar': typeof BuscarRoute
  '/carreras': typeof CarrerasRoute
  '/contacto': typeof ContactoRoute
  '/cuidado-adulto-mayor': typeof CuidadoAdultoMayorRoute
  '/cuidado-paliativo': typeof CuidadoPaliativoRoute
  '/cuidado-pediatrico': typeof CuidadoPediatricoRoute
  '/cuidado-postoperatorio': typeof CuidadoPostoperatorioRoute
  '/cuidador-domicilio': typeof CuidadorDomicilioRoute
  '/cumplimiento': typeof CumplimientoRoute
  '/enfermeria-domiciliaria': typeof EnfermeriaDomiciliariaRoute
  '/evaluador': typeof EvaluadorRoute
  '/familias': typeof FamiliasRoute
  '/habeas-data': typeof HabeasDataRoute
  '/mensajes': typeof MensajesRoute
  '/planes': typeof PlanesRoute
  '/prensa': typeof PrensaRoute
  '/privacidad': typeof PrivacidadRoute
  '/profesionales': typeof ProfesionalesRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/talento-humano': typeof TalentoHumanoRoute
  '/tecnologia': typeof TecnologiaRoute
  '/terminos': typeof TerminosRoute
  '/dashboard/familia': typeof DashboardFamiliaRouteWithChildren
  '/dashboard/institucion': typeof DashboardInstitucionRoute
  '/dashboard/profesional': typeof DashboardProfesionalRoute
  '/dashboard/whatsapp': typeof DashboardWhatsappRoute
  '/oferta/$offerId': typeof OfertaOfferIdRoute
  '/profesional/$proId': typeof ProfesionalProIdRoute
  '/servicio/$bookingId': typeof ServicioBookingIdRoute
  '/superadmin/auditoria': typeof SuperadminAuditoriaRoute
  '/superadmin/crm': typeof SuperadminCrmRoute
  '/superadmin/fraude': typeof SuperadminFraudeRoute
  '/superadmin/marketing': typeof SuperadminMarketingRoute
  '/superadmin/marketplace': typeof SuperadminMarketplaceRoute
  '/superadmin/publicidad': typeof SuperadminPublicidadRoute
  '/dashboard': typeof DashboardIndexRoute
  '/superadmin': typeof SuperadminIndexRoute
  '/dashboard/familia/onboarding': typeof DashboardFamiliaOnboardingRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/auxiliar-enfermeria': typeof AuxiliarEnfermeriaRoute
  '/buscar': typeof BuscarRoute
  '/carreras': typeof CarrerasRoute
  '/contacto': typeof ContactoRoute
  '/cuidado-adulto-mayor': typeof CuidadoAdultoMayorRoute
  '/cuidado-paliativo': typeof CuidadoPaliativoRoute
  '/cuidado-pediatrico': typeof CuidadoPediatricoRoute
  '/cuidado-postoperatorio': typeof CuidadoPostoperatorioRoute
  '/cuidador-domicilio': typeof CuidadorDomicilioRoute
  '/cumplimiento': typeof CumplimientoRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/enfermeria-domiciliaria': typeof EnfermeriaDomiciliariaRoute
  '/evaluador': typeof EvaluadorRoute
  '/familias': typeof FamiliasRoute
  '/habeas-data': typeof HabeasDataRoute
  '/mensajes': typeof MensajesRoute
  '/planes': typeof PlanesRoute
  '/prensa': typeof PrensaRoute
  '/privacidad': typeof PrivacidadRoute
  '/profesionales': typeof ProfesionalesRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/sobre': typeof SobreRoute
  '/superadmin': typeof SuperadminRouteWithChildren
  '/talento-humano': typeof TalentoHumanoRoute
  '/tecnologia': typeof TecnologiaRoute
  '/terminos': typeof TerminosRoute
  '/dashboard/familia': typeof DashboardFamiliaRouteWithChildren
  '/dashboard/institucion': typeof DashboardInstitucionRoute
  '/dashboard/profesional': typeof DashboardProfesionalRoute
  '/dashboard/whatsapp': typeof DashboardWhatsappRoute
  '/oferta/$offerId': typeof OfertaOfferIdRoute
  '/profesional/$proId': typeof ProfesionalProIdRoute
  '/servicio/$bookingId': typeof ServicioBookingIdRoute
  '/superadmin/auditoria': typeof SuperadminAuditoriaRoute
  '/superadmin/crm': typeof SuperadminCrmRoute
  '/superadmin/fraude': typeof SuperadminFraudeRoute
  '/superadmin/marketing': typeof SuperadminMarketingRoute
  '/superadmin/marketplace': typeof SuperadminMarketplaceRoute
  '/superadmin/publicidad': typeof SuperadminPublicidadRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/superadmin/': typeof SuperadminIndexRoute
  '/dashboard/familia/onboarding': typeof DashboardFamiliaOnboardingRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/auxiliar-enfermeria'
    | '/buscar'
    | '/carreras'
    | '/contacto'
    | '/cuidado-adulto-mayor'
    | '/cuidado-paliativo'
    | '/cuidado-pediatrico'
    | '/cuidado-postoperatorio'
    | '/cuidador-domicilio'
    | '/cumplimiento'
    | '/dashboard'
    | '/enfermeria-domiciliaria'
    | '/evaluador'
    | '/familias'
    | '/habeas-data'
    | '/mensajes'
    | '/planes'
    | '/prensa'
    | '/privacidad'
    | '/profesionales'
    | '/reset-password'
    | '/sitemap.xml'
    | '/sobre'
    | '/superadmin'
    | '/talento-humano'
    | '/tecnologia'
    | '/terminos'
    | '/dashboard/familia'
    | '/dashboard/institucion'
    | '/dashboard/profesional'
    | '/dashboard/whatsapp'
    | '/oferta/$offerId'
    | '/profesional/$proId'
    | '/servicio/$bookingId'
    | '/superadmin/auditoria'
    | '/superadmin/crm'
    | '/superadmin/fraude'
    | '/superadmin/marketing'
    | '/superadmin/marketplace'
    | '/superadmin/publicidad'
    | '/dashboard/'
    | '/superadmin/'
    | '/dashboard/familia/onboarding'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/auxiliar-enfermeria'
    | '/buscar'
    | '/carreras'
    | '/contacto'
    | '/cuidado-adulto-mayor'
    | '/cuidado-paliativo'
    | '/cuidado-pediatrico'
    | '/cuidado-postoperatorio'
    | '/cuidador-domicilio'
    | '/cumplimiento'
    | '/enfermeria-domiciliaria'
    | '/evaluador'
    | '/familias'
    | '/habeas-data'
    | '/mensajes'
    | '/planes'
    | '/prensa'
    | '/privacidad'
    | '/profesionales'
    | '/reset-password'
    | '/sitemap.xml'
    | '/sobre'
    | '/talento-humano'
    | '/tecnologia'
    | '/terminos'
    | '/dashboard/familia'
    | '/dashboard/institucion'
    | '/dashboard/profesional'
    | '/dashboard/whatsapp'
    | '/oferta/$offerId'
    | '/profesional/$proId'
    | '/servicio/$bookingId'
    | '/superadmin/auditoria'
    | '/superadmin/crm'
    | '/superadmin/fraude'
    | '/superadmin/marketing'
    | '/superadmin/marketplace'
    | '/superadmin/publicidad'
    | '/dashboard'
    | '/superadmin'
    | '/dashboard/familia/onboarding'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/auxiliar-enfermeria'
    | '/buscar'
    | '/carreras'
    | '/contacto'
    | '/cuidado-adulto-mayor'
    | '/cuidado-paliativo'
    | '/cuidado-pediatrico'
    | '/cuidado-postoperatorio'
    | '/cuidador-domicilio'
    | '/cumplimiento'
    | '/dashboard'
    | '/enfermeria-domiciliaria'
    | '/evaluador'
    | '/familias'
    | '/habeas-data'
    | '/mensajes'
    | '/planes'
    | '/prensa'
    | '/privacidad'
    | '/profesionales'
    | '/reset-password'
    | '/sitemap.xml'
    | '/sobre'
    | '/superadmin'
    | '/talento-humano'
    | '/tecnologia'
    | '/terminos'
    | '/dashboard/familia'
    | '/dashboard/institucion'
    | '/dashboard/profesional'
    | '/dashboard/whatsapp'
    | '/oferta/$offerId'
    | '/profesional/$proId'
    | '/servicio/$bookingId'
    | '/superadmin/auditoria'
    | '/superadmin/crm'
    | '/superadmin/fraude'
    | '/superadmin/marketing'
    | '/superadmin/marketplace'
    | '/superadmin/publicidad'
    | '/dashboard/'
    | '/superadmin/'
    | '/dashboard/familia/onboarding'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  AuxiliarEnfermeriaRoute: typeof AuxiliarEnfermeriaRoute
  BuscarRoute: typeof BuscarRoute
  CarrerasRoute: typeof CarrerasRoute
  ContactoRoute: typeof ContactoRoute
  CuidadoAdultoMayorRoute: typeof CuidadoAdultoMayorRoute
  CuidadoPaliativoRoute: typeof CuidadoPaliativoRoute
  CuidadoPediatricoRoute: typeof CuidadoPediatricoRoute
  CuidadoPostoperatorioRoute: typeof CuidadoPostoperatorioRoute
  CuidadorDomicilioRoute: typeof CuidadorDomicilioRoute
  CumplimientoRoute: typeof CumplimientoRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  EnfermeriaDomiciliariaRoute: typeof EnfermeriaDomiciliariaRoute
  EvaluadorRoute: typeof EvaluadorRoute
  FamiliasRoute: typeof FamiliasRoute
  HabeasDataRoute: typeof HabeasDataRoute
  MensajesRoute: typeof MensajesRoute
  PlanesRoute: typeof PlanesRoute
  PrensaRoute: typeof PrensaRoute
  PrivacidadRoute: typeof PrivacidadRoute
  ProfesionalesRoute: typeof ProfesionalesRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  SobreRoute: typeof SobreRoute
  SuperadminRoute: typeof SuperadminRouteWithChildren
  TalentoHumanoRoute: typeof TalentoHumanoRoute
  TecnologiaRoute: typeof TecnologiaRoute
  TerminosRoute: typeof TerminosRoute
  OfertaOfferIdRoute: typeof OfertaOfferIdRoute
  ProfesionalProIdRoute: typeof ProfesionalProIdRoute
  ServicioBookingIdRoute: typeof ServicioBookingIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/terminos': {
      id: '/terminos'
      path: '/terminos'
      fullPath: '/terminos'
      preLoaderRoute: typeof TerminosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/tecnologia': {
      id: '/tecnologia'
      path: '/tecnologia'
      fullPath: '/tecnologia'
      preLoaderRoute: typeof TecnologiaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/talento-humano': {
      id: '/talento-humano'
      path: '/talento-humano'
      fullPath: '/talento-humano'
      preLoaderRoute: typeof TalentoHumanoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/superadmin': {
      id: '/superadmin'
      path: '/superadmin'
      fullPath: '/superadmin'
      preLoaderRoute: typeof SuperadminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sobre': {
      id: '/sobre'
      path: '/sobre'
      fullPath: '/sobre'
      preLoaderRoute: typeof SobreRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profesionales': {
      id: '/profesionales'
      path: '/profesionales'
      fullPath: '/profesionales'
      preLoaderRoute: typeof ProfesionalesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidad': {
      id: '/privacidad'
      path: '/privacidad'
      fullPath: '/privacidad'
      preLoaderRoute: typeof PrivacidadRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prensa': {
      id: '/prensa'
      path: '/prensa'
      fullPath: '/prensa'
      preLoaderRoute: typeof PrensaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planes': {
      id: '/planes'
      path: '/planes'
      fullPath: '/planes'
      preLoaderRoute: typeof PlanesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mensajes': {
      id: '/mensajes'
      path: '/mensajes'
      fullPath: '/mensajes'
      preLoaderRoute: typeof MensajesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/habeas-data': {
      id: '/habeas-data'
      path: '/habeas-data'
      fullPath: '/habeas-data'
      preLoaderRoute: typeof HabeasDataRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/familias': {
      id: '/familias'
      path: '/familias'
      fullPath: '/familias'
      preLoaderRoute: typeof FamiliasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evaluador': {
      id: '/evaluador'
      path: '/evaluador'
      fullPath: '/evaluador'
      preLoaderRoute: typeof EvaluadorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/enfermeria-domiciliaria': {
      id: '/enfermeria-domiciliaria'
      path: '/enfermeria-domiciliaria'
      fullPath: '/enfermeria-domiciliaria'
      preLoaderRoute: typeof EnfermeriaDomiciliariaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cumplimiento': {
      id: '/cumplimiento'
      path: '/cumplimiento'
      fullPath: '/cumplimiento'
      preLoaderRoute: typeof CumplimientoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cuidador-domicilio': {
      id: '/cuidador-domicilio'
      path: '/cuidador-domicilio'
      fullPath: '/cuidador-domicilio'
      preLoaderRoute: typeof CuidadorDomicilioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cuidado-postoperatorio': {
      id: '/cuidado-postoperatorio'
      path: '/cuidado-postoperatorio'
      fullPath: '/cuidado-postoperatorio'
      preLoaderRoute: typeof CuidadoPostoperatorioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cuidado-pediatrico': {
      id: '/cuidado-pediatrico'
      path: '/cuidado-pediatrico'
      fullPath: '/cuidado-pediatrico'
      preLoaderRoute: typeof CuidadoPediatricoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cuidado-paliativo': {
      id: '/cuidado-paliativo'
      path: '/cuidado-paliativo'
      fullPath: '/cuidado-paliativo'
      preLoaderRoute: typeof CuidadoPaliativoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cuidado-adulto-mayor': {
      id: '/cuidado-adulto-mayor'
      path: '/cuidado-adulto-mayor'
      fullPath: '/cuidado-adulto-mayor'
      preLoaderRoute: typeof CuidadoAdultoMayorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contacto': {
      id: '/contacto'
      path: '/contacto'
      fullPath: '/contacto'
      preLoaderRoute: typeof ContactoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carreras': {
      id: '/carreras'
      path: '/carreras'
      fullPath: '/carreras'
      preLoaderRoute: typeof CarrerasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buscar': {
      id: '/buscar'
      path: '/buscar'
      fullPath: '/buscar'
      preLoaderRoute: typeof BuscarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auxiliar-enfermeria': {
      id: '/auxiliar-enfermeria'
      path: '/auxiliar-enfermeria'
      fullPath: '/auxiliar-enfermeria'
      preLoaderRoute: typeof AuxiliarEnfermeriaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/superadmin/': {
      id: '/superadmin/'
      path: '/'
      fullPath: '/superadmin/'
      preLoaderRoute: typeof SuperadminIndexRouteImport
      parentRoute: typeof SuperadminRoute
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/superadmin/publicidad': {
      id: '/superadmin/publicidad'
      path: '/publicidad'
      fullPath: '/superadmin/publicidad'
      preLoaderRoute: typeof SuperadminPublicidadRouteImport
      parentRoute: typeof SuperadminRoute
    }
    '/superadmin/marketplace': {
      id: '/superadmin/marketplace'
      path: '/marketplace'
      fullPath: '/superadmin/marketplace'
      preLoaderRoute: typeof SuperadminMarketplaceRouteImport
      parentRoute: typeof SuperadminRoute
    }
    '/superadmin/marketing': {
      id: '/superadmin/marketing'
      path: '/marketing'
      fullPath: '/superadmin/marketing'
      preLoaderRoute: typeof SuperadminMarketingRouteImport
      parentRoute: typeof SuperadminRoute
    }
    '/superadmin/fraude': {
      id: '/superadmin/fraude'
      path: '/fraude'
      fullPath: '/superadmin/fraude'
      preLoaderRoute: typeof SuperadminFraudeRouteImport
      parentRoute: typeof SuperadminRoute
    }
    '/superadmin/crm': {
      id: '/superadmin/crm'
      path: '/crm'
      fullPath: '/superadmin/crm'
      preLoaderRoute: typeof SuperadminCrmRouteImport
      parentRoute: typeof SuperadminRoute
    }
    '/superadmin/auditoria': {
      id: '/superadmin/auditoria'
      path: '/auditoria'
      fullPath: '/superadmin/auditoria'
      preLoaderRoute: typeof SuperadminAuditoriaRouteImport
      parentRoute: typeof SuperadminRoute
    }
    '/servicio/$bookingId': {
      id: '/servicio/$bookingId'
      path: '/servicio/$bookingId'
      fullPath: '/servicio/$bookingId'
      preLoaderRoute: typeof ServicioBookingIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profesional/$proId': {
      id: '/profesional/$proId'
      path: '/profesional/$proId'
      fullPath: '/profesional/$proId'
      preLoaderRoute: typeof ProfesionalProIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/oferta/$offerId': {
      id: '/oferta/$offerId'
      path: '/oferta/$offerId'
      fullPath: '/oferta/$offerId'
      preLoaderRoute: typeof OfertaOfferIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/whatsapp': {
      id: '/dashboard/whatsapp'
      path: '/whatsapp'
      fullPath: '/dashboard/whatsapp'
      preLoaderRoute: typeof DashboardWhatsappRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/profesional': {
      id: '/dashboard/profesional'
      path: '/profesional'
      fullPath: '/dashboard/profesional'
      preLoaderRoute: typeof DashboardProfesionalRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/institucion': {
      id: '/dashboard/institucion'
      path: '/institucion'
      fullPath: '/dashboard/institucion'
      preLoaderRoute: typeof DashboardInstitucionRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/familia': {
      id: '/dashboard/familia'
      path: '/familia'
      fullPath: '/dashboard/familia'
      preLoaderRoute: typeof DashboardFamiliaRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/familia/onboarding': {
      id: '/dashboard/familia/onboarding'
      path: '/onboarding'
      fullPath: '/dashboard/familia/onboarding'
      preLoaderRoute: typeof DashboardFamiliaOnboardingRouteImport
      parentRoute: typeof DashboardFamiliaRoute
    }
  }
}

interface DashboardFamiliaRouteChildren {
  DashboardFamiliaOnboardingRoute: typeof DashboardFamiliaOnboardingRoute
}

const DashboardFamiliaRouteChildren: DashboardFamiliaRouteChildren = {
  DashboardFamiliaOnboardingRoute: DashboardFamiliaOnboardingRoute,
}

const DashboardFamiliaRouteWithChildren =
  DashboardFamiliaRoute._addFileChildren(DashboardFamiliaRouteChildren)

interface DashboardRouteChildren {
  DashboardFamiliaRoute: typeof DashboardFamiliaRouteWithChildren
  DashboardInstitucionRoute: typeof DashboardInstitucionRoute
  DashboardProfesionalRoute: typeof DashboardProfesionalRoute
  DashboardWhatsappRoute: typeof DashboardWhatsappRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardFamiliaRoute: DashboardFamiliaRouteWithChildren,
  DashboardInstitucionRoute: DashboardInstitucionRoute,
  DashboardProfesionalRoute: DashboardProfesionalRoute,
  DashboardWhatsappRoute: DashboardWhatsappRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface SuperadminRouteChildren {
  SuperadminAuditoriaRoute: typeof SuperadminAuditoriaRoute
  SuperadminCrmRoute: typeof SuperadminCrmRoute
  SuperadminFraudeRoute: typeof SuperadminFraudeRoute
  SuperadminMarketingRoute: typeof SuperadminMarketingRoute
  SuperadminMarketplaceRoute: typeof SuperadminMarketplaceRoute
  SuperadminPublicidadRoute: typeof SuperadminPublicidadRoute
  SuperadminIndexRoute: typeof SuperadminIndexRoute
}

const SuperadminRouteChildren: SuperadminRouteChildren = {
  SuperadminAuditoriaRoute: SuperadminAuditoriaRoute,
  SuperadminCrmRoute: SuperadminCrmRoute,
  SuperadminFraudeRoute: SuperadminFraudeRoute,
  SuperadminMarketingRoute: SuperadminMarketingRoute,
  SuperadminMarketplaceRoute: SuperadminMarketplaceRoute,
  SuperadminPublicidadRoute: SuperadminPublicidadRoute,
  SuperadminIndexRoute: SuperadminIndexRoute,
}

const SuperadminRouteWithChildren = SuperadminRoute._addFileChildren(
  SuperadminRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  AuxiliarEnfermeriaRoute: AuxiliarEnfermeriaRoute,
  BuscarRoute: BuscarRoute,
  CarrerasRoute: CarrerasRoute,
  ContactoRoute: ContactoRoute,
  CuidadoAdultoMayorRoute: CuidadoAdultoMayorRoute,
  CuidadoPaliativoRoute: CuidadoPaliativoRoute,
  CuidadoPediatricoRoute: CuidadoPediatricoRoute,
  CuidadoPostoperatorioRoute: CuidadoPostoperatorioRoute,
  CuidadorDomicilioRoute: CuidadorDomicilioRoute,
  CumplimientoRoute: CumplimientoRoute,
  DashboardRoute: DashboardRouteWithChildren,
  EnfermeriaDomiciliariaRoute: EnfermeriaDomiciliariaRoute,
  EvaluadorRoute: EvaluadorRoute,
  FamiliasRoute: FamiliasRoute,
  HabeasDataRoute: HabeasDataRoute,
  MensajesRoute: MensajesRoute,
  PlanesRoute: PlanesRoute,
  PrensaRoute: PrensaRoute,
  PrivacidadRoute: PrivacidadRoute,
  ProfesionalesRoute: ProfesionalesRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  SobreRoute: SobreRoute,
  SuperadminRoute: SuperadminRouteWithChildren,
  TalentoHumanoRoute: TalentoHumanoRoute,
  TecnologiaRoute: TecnologiaRoute,
  TerminosRoute: TerminosRoute,
  OfertaOfferIdRoute: OfertaOfferIdRoute,
  ProfesionalProIdRoute: ProfesionalProIdRoute,
  ServicioBookingIdRoute: ServicioBookingIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
