/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TalentoHumanoRouteImport } from './routes/talento-humano'
import { Route as SuperadminRouteImport } from './routes/superadmin'
import { Route as PlanesRouteImport } from './routes/planes'
import { Route as MensajesRouteImport } from './routes/mensajes'
import { Route as EvaluadorRouteImport } from './routes/evaluador'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as BuscarRouteImport } from './routes/buscar'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SuperadminFraudeRouteImport } from './routes/superadmin.fraude'
import { Route as DashboardProfesionalRouteImport } from './routes/dashboard.profesional'
import { Route as DashboardInstitucionRouteImport } from './routes/dashboard.institucion'
import { Route as DashboardFamiliaRouteImport } from './routes/dashboard.familia'

const TalentoHumanoRoute = TalentoHumanoRouteImport.update({
  id: '/talento-humano',
  path: '/talento-humano',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperadminRoute = SuperadminRouteImport.update({
  id: '/superadmin',
  path: '/superadmin',
  getParentRoute: () => rootRouteImport,
} as any)
const PlanesRoute = PlanesRouteImport.update({
  id: '/planes',
  path: '/planes',
  getParentRoute: () => rootRouteImport,
} as any)
const MensajesRoute = MensajesRouteImport.update({
  id: '/mensajes',
  path: '/mensajes',
  getParentRoute: () => rootRouteImport,
} as any)
const EvaluadorRoute = EvaluadorRouteImport.update({
  id: '/evaluador',
  path: '/evaluador',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const BuscarRoute = BuscarRouteImport.update({
  id: '/buscar',
  path: '/buscar',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SuperadminFraudeRoute = SuperadminFraudeRouteImport.update({
  id: '/fraude',
  path: '/fraude',
  getParentRoute: () => SuperadminRoute,
} as any)
const DashboardProfesionalRoute = DashboardProfesionalRouteImport.update({
  id: '/profesional',
  path: '/profesional',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardInstitucionRoute = DashboardInstitucionRouteImport.update({
  id: '/institucion',
  path: '/institucion',
  getParentRoute: () => DashboardRoute,
} as any)
const DashboardFamiliaRoute = DashboardFamiliaRouteImport.update({
  id: '/familia',
  path: '/familia',
  getParentRoute: () => DashboardRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/buscar': typeof BuscarRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/evaluador': typeof EvaluadorRoute
  '/mensajes': typeof MensajesRoute
  '/planes': typeof PlanesRoute
  '/superadmin': typeof SuperadminRouteWithChildren
  '/talento-humano': typeof TalentoHumanoRoute
  '/dashboard/familia': typeof DashboardFamiliaRoute
  '/dashboard/institucion': typeof DashboardInstitucionRoute
  '/dashboard/profesional': typeof DashboardProfesionalRoute
  '/superadmin/fraude': typeof SuperadminFraudeRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/buscar': typeof BuscarRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/evaluador': typeof EvaluadorRoute
  '/mensajes': typeof MensajesRoute
  '/planes': typeof PlanesRoute
  '/superadmin': typeof SuperadminRouteWithChildren
  '/talento-humano': typeof TalentoHumanoRoute
  '/dashboard/familia': typeof DashboardFamiliaRoute
  '/dashboard/institucion': typeof DashboardInstitucionRoute
  '/dashboard/profesional': typeof DashboardProfesionalRoute
  '/superadmin/fraude': typeof SuperadminFraudeRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/buscar': typeof BuscarRoute
  '/dashboard': typeof DashboardRouteWithChildren
  '/evaluador': typeof EvaluadorRoute
  '/mensajes': typeof MensajesRoute
  '/planes': typeof PlanesRoute
  '/superadmin': typeof SuperadminRouteWithChildren
  '/talento-humano': typeof TalentoHumanoRoute
  '/dashboard/familia': typeof DashboardFamiliaRoute
  '/dashboard/institucion': typeof DashboardInstitucionRoute
  '/dashboard/profesional': typeof DashboardProfesionalRoute
  '/superadmin/fraude': typeof SuperadminFraudeRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/buscar'
    | '/dashboard'
    | '/evaluador'
    | '/mensajes'
    | '/planes'
    | '/superadmin'
    | '/talento-humano'
    | '/dashboard/familia'
    | '/dashboard/institucion'
    | '/dashboard/profesional'
    | '/superadmin/fraude'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/buscar'
    | '/dashboard'
    | '/evaluador'
    | '/mensajes'
    | '/planes'
    | '/superadmin'
    | '/talento-humano'
    | '/dashboard/familia'
    | '/dashboard/institucion'
    | '/dashboard/profesional'
    | '/superadmin/fraude'
  id:
    | '__root__'
    | '/'
    | '/auth'
    | '/buscar'
    | '/dashboard'
    | '/evaluador'
    | '/mensajes'
    | '/planes'
    | '/superadmin'
    | '/talento-humano'
    | '/dashboard/familia'
    | '/dashboard/institucion'
    | '/dashboard/profesional'
    | '/superadmin/fraude'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRoute
  BuscarRoute: typeof BuscarRoute
  DashboardRoute: typeof DashboardRouteWithChildren
  EvaluadorRoute: typeof EvaluadorRoute
  MensajesRoute: typeof MensajesRoute
  PlanesRoute: typeof PlanesRoute
  SuperadminRoute: typeof SuperadminRouteWithChildren
  TalentoHumanoRoute: typeof TalentoHumanoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/talento-humano': {
      id: '/talento-humano'
      path: '/talento-humano'
      fullPath: '/talento-humano'
      preLoaderRoute: typeof TalentoHumanoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/superadmin': {
      id: '/superadmin'
      path: '/superadmin'
      fullPath: '/superadmin'
      preLoaderRoute: typeof SuperadminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/planes': {
      id: '/planes'
      path: '/planes'
      fullPath: '/planes'
      preLoaderRoute: typeof PlanesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mensajes': {
      id: '/mensajes'
      path: '/mensajes'
      fullPath: '/mensajes'
      preLoaderRoute: typeof MensajesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/evaluador': {
      id: '/evaluador'
      path: '/evaluador'
      fullPath: '/evaluador'
      preLoaderRoute: typeof EvaluadorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/buscar': {
      id: '/buscar'
      path: '/buscar'
      fullPath: '/buscar'
      preLoaderRoute: typeof BuscarRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/superadmin/fraude': {
      id: '/superadmin/fraude'
      path: '/fraude'
      fullPath: '/superadmin/fraude'
      preLoaderRoute: typeof SuperadminFraudeRouteImport
      parentRoute: typeof SuperadminRoute
    }
    '/dashboard/profesional': {
      id: '/dashboard/profesional'
      path: '/profesional'
      fullPath: '/dashboard/profesional'
      preLoaderRoute: typeof DashboardProfesionalRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/institucion': {
      id: '/dashboard/institucion'
      path: '/institucion'
      fullPath: '/dashboard/institucion'
      preLoaderRoute: typeof DashboardInstitucionRouteImport
      parentRoute: typeof DashboardRoute
    }
    '/dashboard/familia': {
      id: '/dashboard/familia'
      path: '/familia'
      fullPath: '/dashboard/familia'
      preLoaderRoute: typeof DashboardFamiliaRouteImport
      parentRoute: typeof DashboardRoute
    }
  }
}

interface DashboardRouteChildren {
  DashboardFamiliaRoute: typeof DashboardFamiliaRoute
  DashboardInstitucionRoute: typeof DashboardInstitucionRoute
  DashboardProfesionalRoute: typeof DashboardProfesionalRoute
}

const DashboardRouteChildren: DashboardRouteChildren = {
  DashboardFamiliaRoute: DashboardFamiliaRoute,
  DashboardInstitucionRoute: DashboardInstitucionRoute,
  DashboardProfesionalRoute: DashboardProfesionalRoute,
}

const DashboardRouteWithChildren = DashboardRoute._addFileChildren(
  DashboardRouteChildren,
)

interface SuperadminRouteChildren {
  SuperadminFraudeRoute: typeof SuperadminFraudeRoute
}

const SuperadminRouteChildren: SuperadminRouteChildren = {
  SuperadminFraudeRoute: SuperadminFraudeRoute,
}

const SuperadminRouteWithChildren = SuperadminRoute._addFileChildren(
  SuperadminRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRoute,
  BuscarRoute: BuscarRoute,
  DashboardRoute: DashboardRouteWithChildren,
  EvaluadorRoute: EvaluadorRoute,
  MensajesRoute: MensajesRoute,
  PlanesRoute: PlanesRoute,
  SuperadminRoute: SuperadminRouteWithChildren,
  TalentoHumanoRoute: TalentoHumanoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
